### ISSUE TITLE
Inputs via the command line

### ISSUE THREAD

**Issue by kaushiksv** [srisham/wizlightcpp#4]
வணக்கம் / Hello !

I think it would be better to provide the inputs like IP address and scene setting via the command line argument.

Easiest is to add a shell script. I've also used gengetopt to parse argc and argv.

Any recommendation? I'd be happy to create a fork and create a PR in free time.

br,
Kaushik

**Comment by srisham** [comment]
Hi Kauhsik,

Passing command line arguments are already supported. You can use the following way:

wizlightcpp <command> --ip <ipaddress>

To find out what params to be passed for each commamd, you can run the following:

wizlightcpp <command> --help

**Comment by kaushiksv** [comment]
Doesn't work. I built from master branch, commit 5a6e33b34d18860c6a5489e8b50b0263e1a7ef2e.
![image](https://user-images.githubusercontent.com/4756704/184464062-74e22987-7959-4805-bfb4-9ce7bcd74beb.png)

**Comment by srisham** [comment]
Try without any quote.

wizlightcpp off --ip 192.168.1.102

**Comment by srisham** [comment]
Got the issue. I will fix it and update you.

**Comment by srisham** [comment]
@kaushiksv 

Fixed it and updated the master branch. Also, updated the usage details in the README doc.
Please let me know if it resolves the issue.

**Comment by kaushiksv** [comment]
Hi,

Thanks for the fix.

Looks like only on/off and get commands accept the --ip switch.

The set commands still don't work.

```

kaushik@kaushik-ubuntu-ssd:~/repos/wizlightcpp/build$ ./wizlightcpp getdeviceinfo --ip 192.168.1.102
{
    "bulb_response": {
        "result": {
            "mac": "6c29902767bb",
            "devMac": "6c29902767bb",
            "moduleName": "ESP03_SHRGB1C_01"
        }
    }
}
kaushik@kaushik-ubuntu-ssd:~/repos/wizlightcpp/build$ ./wizlightcpp setcolortemp 5000 --ip 192.168.1.102
Unknown Option

Usage: wizlightcpp setcolortemp {OPTIONS}
Try 'wizlightcpp setcolortemp --help' for help.
kaushik@kaushik-ubuntu-ssd:~/repos/wizlightcpp/build$ ./wizlightcpp setcolortemp
Enter the bulb IP address:192.168.1.102
Enter the color temperature in kelvins [1000 to 8000]:5000
{
    "bulb_response": {
        "result": {
            "success": true
        }
    }
}

```

**Comment by srisham** [comment]
@kaushiksv 

setcolortemp requires two arguments and you may need to pass the '--temp' argument along with the value 5000.
Example:
`$ wizlightcpp setcolortemp --ip 192.168.1.152 --temp 8000
`

Try help option to see list of all arguments:
```
$ wizlightcpp setcolortemp --help
Usage: wizlightcpp setcolortemp {OPTIONS}

Options:
--ip                    IP address of the bulb.
--help                  Show this message and exit.
--temp                  Color temperature in kelvins [1000 to 8000].

```

**Comment by kaushiksv** [comment]
Hi,

yes, it works. My bad, didn't notice it. Thanks for the fix, and the repo.
